### ISSUE TITLE
[150] Client-side list fetches don't save total.entities and total.pages properly

### ISSUE THREAD

**Issue by luisherranz** [frontity/wp-org-connection#42]
If a list is fetched in the server, `list.total.entities` and `list.total.pages` are defined but if a list is fetched in the client the are `undefined`. This means users can only scroll down and get the next pages of the list which was rendered in SSR, but they can't if the swipe to another category/tag.

Size: **all sites (2M)**
Environment: **production (x5)**
Range: **medium (x3)**
Behaviour: **not-nice (x1)**
Mass: **everyone (x5)**
PRIORITY: **[150]**

**Comment by DAreRodz** [comment]
It was a CORS problem in frontity.cloud, `x-wp-total` and `x-wp-totalpages` headers were not accessible for [WP-API](https://github.com/wp-api/node-wpapi) and thus the property `_paging` that we use [here](https://github.com/frontity/wp-org-connection/blob/dev/src/pwa/stores/connection/index.js#L114#L119) and [here](https://github.com/frontity/wp-org-connection/blob/dev/src/pwa/stores/connection/index.js#L151#L156) was `undefined`.

Fixed in https://github.com/frontity/cloud/pull/12
